controllers/PostController.php
<?php

namespace app\controllers;

use app\models\category\Category;
use app\models\Material;
use app\models\Tag;
use Yii;
use app\models\post\Post;
use app\models\post\PostSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\components\UserPermissions;
use yii\web\ForbiddenHttpException;
use app\components\feed\Feed;
use app\components\feed\Item;
use yii\helpers\HtmlPurifier;
use yii\helpers\Markdown;
use yii\helpers\Url;
use app\helpers\Text;
use yii\web\UploadedFile;

/**
 * PostController implements the CRUD actions for Post model.
 *
 * @package app\controllers
 *
 * @author Alexander Schilling
 */
class PostController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only'  => ['index', 'view', 'category', 'tag', 'create', 'admin', 'update', 'delete', 'rss'],
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => ['index', 'view', 'category', 'tag', 'rss'],
                        'roles'   => ['?', '@'],
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['create', 'update', 'admin', 'delete'],
                        'roles'   => [UserPermissions::ADMIN_POST],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all posts
     *
     * @param null $id
     * @return mixed
     */
    public function actionIndex($id = null)
    {

        $this->layout = "/page";

        $searchModel = new PostSearch([
            'sortBy' => (int) $id,
        ]);

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string
     */
    public function actionAdmin()
    {
        $searchModel = new PostSearch();

        $dataProvider = $searchModel->adminSearch(Yii::$app->request->queryParams);

        return $this->render(
            'admin',
            [
                'searchModel'  => $searchModel,
                'dataProvider' => $dataProvider,
            ]
        );
    }

    /**
     * Display a single post model
     *
     * @param $slug
     *
     * @return string
     *
     * @throws NotFoundHttpException
     */
    public function actionView($slug)
    {

        $this->layout = "/blog";

        $model = Post::find()->where([
            'status_id' => Material::STATUS_PUBLIC,
            'slug' => $slug,
        ])->withCommentsCount()->one();

        if (!$model) {
            throw new NotFoundHttpException('Запись не найдена.');
        }

        $model->countHits(Material::MATERIAL_POST_NAME);

        return $this->render('view', ['model' => $model]);
    }

    /**
     * Creates a new Post model
     *
     * If creation is successful, the browser will be redirected to the 'admin' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Post();

        if ($model->load(Yii::$app->request->post())) {

            $model->preview_img_file = UploadedFile::getInstance($model, 'preview_img_file');

            if ($model->save()) {
                Yii::$app->getSession()->setFlash('success', 'Запись добавлена!');
                return $this->redirect(['post/update', 'id' => $model->id]);
            }
        }

        return $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing Post model
     *
     * If update is successful, the browser will be redirected to the 'admin' page
     *
     * @param integer $id
     *
     * @return mixed
     *
     * @throws ForbiddenHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            $model->preview_img_file = UploadedFile::getInstance($model, 'preview_img_file');

            if ($model->save()) {
                Yii::$app->getSession()->setFlash('success', 'Запись сохранена!');

                return $this->redirect(['post/update', 'id' => $model->id]);
            }
        }

        return $this->render('update', ['model' => $model]);
    }

    /**
     * Deletes an existing Post model
     *
     * If deletion is successful, the browser will be redirected to the 'index' page
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['admin']);
    }

    /**
     * Action tag
     *
     * @param $tagName
     *
     * @throws NotFoundHttpException
     *
     * @return string
     */
    public function actionTag($tagName)
    {

        $this->layout = "/page";

        $tag = Tag::findOne(['slug' => $tagName]);

        if (!$tag) {
            throw new NotFoundHttpException("Такой тэг не найден.");
        }

        $searchModel = new PostSearch([
            'tagId' => $tag->id,
        ]);

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('tag', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
            'tag'          => $tag
        ]);
    }

    /**
     * Action category
     *
     * @param $categoryName
     *
     * @return string
     *
     * @throws NotFoundHttpException
     */
    public function actionCategory($categoryName)
    {
        $this->layout = "/page";

        $category = Category::findOne([
            'slug' => $categoryName,
            'material_id' => Material::MATERIAL_POST_ID
        ]);

        if (!$category) {
            throw new NotFoundHttpException("Категория не найдена.");
        }

        $searchModel = new PostSearch([
            'categoryId' => $category->id,
        ]);

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('category', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
            'category'     => $category
        ]);
    }

    /**
     * List of posts for rss
     *
     * @return void
     */
    public function actionRss(): void
    {

        /** @var Post[] $posts */
        $posts = Post::find()->where(['status_id' => Post::STATUS_PUBLIC, 'ontop' => Post::SHOW_ON_TOP])->orderBy('datecreate DESC')->limit(10)->all();

        $feed = new Feed();
        $feed->title = \Yii::$app->params['site']['name'];
        $feed->link = Url::to(\Yii::$app->params['site']['url']);
        $feed->selfLink = Url::to(['post/rss'], true);
        $feed->description = 'RSS лента сайта ' .\Yii::$app->params['site']['name'];
        $feed->language = Yii::$app->language;
        $feed->setWebMaster(\Yii::$app->params['adminEmail'], \Yii::$app->params['site']['author']);
        $feed->setManagingEditor(\Yii::$app->params['adminEmail'], \Yii::$app->params['site']['author']);

        foreach ($posts as $post) {
            $item = new Item();
            $item->title = $post->title;
            $item->link = Url::to(['post/view', 'slug' => $post->slug], true);
            $item->guid = Url::to(['post/view', 'slug' => $post->slug], true);
            $item->description = Text::cut('[cut]', Text::cut('[premium]', HtmlPurifier::process(Markdown::process($post->content, 'gfm'), ['HTML.Nofollow' => true])));
            $item->pubDate = $post->datecreate;
            $item->setAuthor(\Yii::$app->params['adminEmail'], $post->user->username);
            $feed->addItem($item);
        }

        $feed->render();
    }

    /**
     * Finds the Post model based on its primary key value
     *
     * If the model is not found, a 404 HTTP exception will be thrown
     *
     * @param integer $id
     *
     * @return Post the loaded model
     *
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Статья не найдена.');
    }
}

controllers/TagController.php
<?php

namespace app\controllers;

use Yii;

/**
 * Class TagController
 *
 * @package app\controllers
 *
 * @author Alexander Schilling
 */
class TagController extends \yii\web\Controller
{

    /**
     * @param null $q
     * @param null $id
     *
     * @return array
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionSearch($q = null, $id = null)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $out = ['results' => ['id' => '', 'text' => '']];

        if ($q !== null) {
            $data = \app\models\Tag::find()
                       ->select('name AS id, name AS text')
                       ->where('name LIKE :q', [':q' => '%' . addcslashes($q, '%_') . '%'])
                       ->limit(20)
                       ->asArray()
                       ->all();

            $out['results'] = array_values($data);
        } elseif ($id > 0) {
            $out['results'] = ['id' => $id, 'text' => $this->findModel($id)->name];
        }

        return $out;
    }

    /**
     * Finds the Tag model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param string $id
     *
     * @return \app\models\Tag the loaded model
     * @throws \yii\web\NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = \app\models\Tag::findOne($id)) !== null) {
            return $model;
        }

        throw new \yii\web\NotFoundHttpException('The requested page does not exist.');
    }
}

views/post/_comments.php
<h3 class="comment-box__title">Оставьте комментарий!</h3>

<p>Если у Вас остались какие-либо вопросы, либо у Вас есть желание высказаться по поводу этой статьи, то Вы можете
    оставить свой комментарий:</p>

<?php

use yii\helpers\Url;

echo \demi\comments\frontend\widgets\Comments::widget(
    [
        // From config file "types" array key (1 => 'Publication')
        'materialType'    => 1,
        // You Publication model unique identifier
        // If you don't have this value simply type your unique key eg: "123",
        // for clarify code you can make const ABOUT_PAGE_COMMENTS_ID = 123
        'materialId'      => $model->id,

        // RECOMENDED FOR FIRST RUN COMMENTED OPTIONS BELOW AND CUSTOMIZED IT AFTER TESTING
        // HTML-options for main comments ul-tag
        'options'         => [
            'class' => 'comments list-unstyled',
        ],
        // HTML-options for nested comments ul-tag
        'nestedOptions'   => [
            'class' => 'comments reply list-unstyled',
        ],
        // jQuery-plugin options, see all options: vendor/demi/comments/frontend/widgets/assets/js/comments.js:55
        'clientOptions'   => [
            'deleteComfirmText'      => 'Вы уверены что хотите удалить данный комментарий?',
            'updateButtonText'       => 'Обновить',
            'cancelUpdateButtonText' => 'Отменить',
            'commentTextSelector' => '.comment-text > div',
        ],
        // Maximum nested level. If level reached - nested comments will be outputted without ul-tag.
        'maxNestedLevel'  => 5,
        // Url for permalink (without '#')
        'materialViewUrl' => Url::to(['view', 'id' => $model->id]),
        // ActiveForm configuration
        'formConfig'      => [
            'enableClientValidation' => true,
            'enableAjaxValidation'   => false,
        ],
    ]
); ?>

views/post/_form.php
<?php

use app\components\UserPermissions;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use yii\web\JsExpression;
use kartik\select2\Select2;
use app\assets\MarkdownEditorAsset;

/* @var $this yii\web\View */
/* @var $model app\models\post\Post */
/* @var $form yii\widgets\ActiveForm */

MarkdownEditorAsset::register($this);

if (!is_array($model->form_tags) && !$model->isNewRecord) {
    $model->form_tags = ArrayHelper::map($model->tags, 'name', 'name');
} else {
    $model->form_tags = [];
}

?>

<div class="post-form">

    <?php $form = ActiveForm::begin(['id' => 'form-post']); ?>

    <div class="form-row">

        <div class="row">
            <div class="col">
                <div class="form-group col-md-8">
                    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
                </div>
            </div>

            <div class="col">
                <div class="form-group col-md-4">
                    <?= $form->field($model, 'slug')->textInput(['maxlength' => true]) ?>
                </div>
            </div>

        </div>

    </div>

    <div class="row">

        <div class="col">
            <div class="form-group col-md-2">
                <?= $form->field($model, 'category_id')->dropDownList(ArrayHelper::map(\app\models\category\Category::getAllCategories(\app\models\Material::MATERIAL_POST_ID), 'id', 'name'), ['prompt' => 'Выберите категорию']); ?>
            </div>
        </div>

        <div class="col">
            <div class="form-group col-md-4">
                    <?= $form->field($model, 'form_tags')->widget(
                        Select2::class,
                        [
                            'options'       => [
                                'placeholder' => \Yii::t('app/blog', 'find_tags'),
                                'multiple'    => true,
                            ],
                            'data'          => $model->form_tags,
                            'pluginOptions' => [
                                'tags'               => true,
                                'tokenSeparators'    => [','],
                                'minimumInputLength' => 2,
                                'maximumInputLength' => 20,
                                'allowClear'         => true,
                                'initSelection'      => new JsExpression(
                                    '
                function (element, callback) {
                    var data = [];
                    $(element.val()).each(function () {
                        data.push({id: this, text: this});
                    });
                    callback(data);
                }
            '
                                ),
                                'ajax'               => [
                                    'url'      => Url::to(['tag/search']),
                                    'dataType' => 'json',
                                    'data'     => new JsExpression('function(params) { return {q:params.term}; }')
                                ],
                            ],
                        ]
                    );
                    ?>
            </div>
        </div>

        <div class="col">
            <div class="form-group col-md-2">
                <?= $form->field($model, 'premium')->dropDownList([
                    '0' => \Yii::t('app', 'no'),
                    '1' => \Yii::t('app', 'yes')
                ]) ?>
            </div>
        </div>

        <div class="col">
            <div class="form-group col-md-4">
                <?= $form->field($model, 'meta_description')->textInput(['maxlength' => true]) ?>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col">
            <div class="col-md-12">
                <?= $form->field($model, 'preview_img_file')->fileInput(); ?>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col">

            <div class="col-md-12">
                <?= $form->field(
                    $model,
                    'content',
                    [
                        'template' => "{label}\n{error}\n{input}\n{hint}"
                    ]
                )->textarea(['class' => 'markdown-editor']) ?>
            </div>

        </div>

    </div>

    <div class="row">

        <div class="col">
            <div class="form-group col-md-4">
                <?= $form->field($model, 'status_id')->dropDownList($model->getStatuses()) ?>
            </div>
        </div>

        <div class="col">
            <div class="form-group col-md-4">
                <?= $form->field($model, 'allow_comments')->dropDownList([
                    '1' => \Yii::t('app', 'yes'),
                    '0' => \Yii::t('app', 'no')
                ]) ?>
            </div>
        </div>

        <div class="col">
            <div class="form-group col-md-4">
                <?= $form->field($model, 'ontop')->dropDownList([
                    '1' => \Yii::t('app', 'yes'),
                    '0' => \Yii::t('app', 'no')
                ]) ?>
            </div>
        </div>

    </div>

    <div class="form-row">

        <div class="col">
            <div class="form-group">
                <?= Html::submitButton(
                    \Yii::t('app', 'button_save'),
                    ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']
                ) ?>
            </div>

        </div>

    </div>

    <?php ActiveForm::end(); ?>
</div>

views/post/_post_footer.php
<?php

use yii\helpers\Html;
use app\helpers\Text;

/* @var $model app\models\post\Post */

?>

<div class="content_footer">

    <i class="fa fa-clock-o"></i> <?= date('d.m.Y', Html::encode($model->datecreate)); ?>

    <i class="fa fa-eye"></i> <?= Html::encode($model->hits); ?>

    <?php if ($model->commentsAllowed()) : ?>
        <i class="fa fa-comments"></i> <?= Html::encode($model->commentsCount); ?>
    <?php endif; ?>

    <?php if (isset($model->category->name)) : ?>
        <i class="fa fa-folder"></i> <?= Html::a($model->category->name, '/category/' . $model->category->slug); ?>
    <?php endif; ?>

    <?php if (!empty($model->tags)) : ?>
        <i class="fa fa-tags"></i> <?= Text::getTagsList($model); ?>
    <?php endif; ?>

</div>

views/post/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\post\PostSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-search">

    <?php $form = ActiveForm::begin(
        [
            'action' => ['admin'],
            'method' => 'get',
        ]
    ); ?>

    <?= $form->field($model, 'title') ?>

    <div class="form-group">
        <?= Html::submitButton('Найти', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Сбросить', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/_view.php
<?php

use yii\helpers\Html;
use app\helpers\Text;
use yii\helpers\HtmlPurifier;
use yii\helpers\Markdown;

/* @var $this yii\web\View */
/* @var $model app\models\post\Post */

?>
<div class="post-view">

    <div class="index_title">
        <h3><?= Html::a($model->title, ['post/view', 'slug' => $model->slug]); ?></h3>
        <?php if ($model->reading_time) : ?>
            <div class="content_header">
                <i class="fa fa-clock-o" aria-hidden="true"></i> Время прочтения ~<?= $model->reading_time; ?> мин.
            </div>
        <?php endif; ?>
        <?php if (!empty($model->preview_img)) : ?>
            <p><?= Html::a('<img src="/' . $model->preview_img . '" alt="' . $model->title . '" />', ['post/view', 'slug' => $model->slug]) ?></p>
        <?php endif; ?>
    </div>

    <?= Text::cut('[cut]',
        Text::cut('[premium]', HtmlPurifier::process(Markdown::process($model->content, 'gfm'), ['HTML.Nofollow' => true])),
        Html::a('Подробнее →', ['post/view', 'slug' => $model->slug])
    ); ?>

</div>

views/post/admin.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\post\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = \Yii::t('app/blog', 'posts');
$this->params['breadcrumbs'][] = $this->title;

$this->registerMetaTag(['name' => 'robots', 'content' => 'noindex']);
?>
<div class="post-admin">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(\Yii::t('app/blog', 'button_add_new_post'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?php Pjax::begin(); ?>    <?= GridView::widget(
        [
            'dataProvider' => $dataProvider,
            'filterModel'  => $searchModel,
            'columns'      => [
                ['class' => 'yii\grid\SerialColumn'],
                'title',
                [
                    'attribute' => 'status_id',
                    'label'     => \Yii::t('app/blog', 'status_id'),
                    'value'     => function ($model) {
                        return $model->getStatusLabel();
                    }
                ],
                [
                    'attribute' => 'hits',
                    'label' => \Yii::t('app/blog', 'hits'),
                    'value' => function ($model) {
                        return $model->hits;
                    }
                ],
                [
                    'attribute' => 'comments',
                    'label' => \Yii::t('app/blog', 'comments'),
                    'value' => function ($model) {
                        return $model->commentsCount;
                    }
                ],
                [
                    'attribute' => 'ontop',
                    'label'     => \Yii::t('app/blog', 'ontop'),
                    'value'     => function ($model) {
                        return $model->ontop ? \Yii::t('app', 'yes') : \Yii::t('app', 'no');
                    }
                ],

                [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{view} {update} {delete}',
                        'buttons' => [
                            'view' => function ($url, $model) {
                                return Html::a(
                                    '<span class="glyphicon glyphicon-eye-open"></span>',
                                    ['post/view', 'slug' => $model->slug]
                                );
                            },
                        ],
                ],

            ],
        ]
    ); ?>
    <?php Pjax::end(); ?></div>

views/post/index.php
<?php

use app\components\UserPermissions;
use app\helpers\Text;
use yii\helpers\Html;
use yii\helpers\Url;
use \yii\widgets\ListView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\post\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = \Yii::$app->params['site']['name'];

$this->registerMetaTag(['name' => 'title', 'content' => \Yii::$app->params['site']['name']]);
$this->registerMetaTag(['name' => 'description', 'content' => \Yii::$app->params['site']['description']]);
$this->registerMetaTag(['name' => 'robots', 'content' => 'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1']);

$this->registerLinkTag(['rel' => 'canonical', 'href' => Url::to(\Yii::$app->params['site']['url'])]);
?>
<div class="post-index">

    <div class="post-header text-center">
        <h1>
            <?php if (UserPermissions::canAdminPost()) : ?>
                <?= Html::a('<i class="fas fa-feather" style="color: #fff"></i>', ['/post/create']) ?>
            <?php else : ?>
                <i class="fas fa-feather"></i>
            <?php endif; ?>
            <?= \Yii::$app->params['site']['name'] ?>
        </h1>
    </div>

    <material-sort
        :data='`<?= Text::arrayToJson([
            [
                'icon' => 'fa fa-clock',
                'name' => \Yii::t('app', 'sort_new'),
                'url'  => Url::toRoute(['/post/index'])
            ],
            [
                'icon' => 'fa fa-eye',
                'name' => \Yii::t('app', 'sort_hits'),
                'url'  => Url::toRoute(['/post/index/1'])
            ],
            [
                'icon' => 'fa fa-comments',
                'name' => \Yii::t('app', 'sort_comments'),
                'url'  => Url::toRoute(['/post/index/2'])
            ],
        ]); ?>`'
    ></material-sort>

    <?php Pjax::begin(); ?>
      <?= ListView::widget(
          [
              'dataProvider' => $dataProvider,
              'emptyText'    => \Yii::t('app/blog', 'records_not_found'),
              'itemView'     => '_view',
              'layout'       => "{items}{pager}",
          ]
      ); ?>
    <?php Pjax::end(); ?>
</div>

views/post/view.php
<?php

use app\components\UserPermissions;
use app\helpers\Text;
use app\models\ad\Ad;
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\Markdown;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\post\Post */

$this->title = Html::encode($model->title);

$this->params['breadcrumbs'][] = ['label' => 'Блог', 'url' => ['/post/index']];
$this->params['breadcrumbs'][] = $this->title;

$this->registerMetaTag(['name' => 'title', 'content' => $model->title]);
$this->registerMetaTag(['name' => 'description', 'content' => $model->meta_description]);
$this->registerMetaTag(['name' => 'robots', 'content' => 'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1']);

$currentPage = Url::to(['post/view', 'slug' => $model->slug], true);

$this->registerLinkTag(['rel' => 'canonical', 'href' => $currentPage]);

/**
 * https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started
 * https://cards-dev.twitter.com/validator
 */
$this->registerMetaTag(['name' => 'twitter:card', 'content' => 'summary_large_image']);
$this->registerMetaTag(['name' => 'twitter:site', 'content' => \Yii::$app->params['site']['twitter']]);
$this->registerMetaTag(['name' => 'twitter:domain', 'content' => \Yii::$app->params['site']['description']]);
$this->registerMetaTag(['name' => 'twitter:creator', 'content' => \Yii::$app->params['site']['twitter']]);
$this->registerMetaTag(['name' => 'twitter:url', 'content' => $currentPage]);
$this->registerMetaTag(['name' => 'twitter:title', 'content' => $model->title]);
$this->registerMetaTag(['name' => 'twitter:description', 'content' => $model->meta_description]);
$this->registerMetaTag(['name' => 'twitter:image:src', 'content' => \Yii::$app->params['site']['url'] . $model->preview_img]);

/**
 * https://ogp.me
 */
$this->registerMetaTag(['name' => 'og:type', 'content' => 'article']);
$this->registerMetaTag(['name' => 'og:title', 'content' => $model->title]);
$this->registerMetaTag(['name' => 'og:description', 'content' => $model->meta_description]);
$this->registerMetaTag(['name' => 'og:url', 'content' => $currentPage]);
$this->registerMetaTag(['name' => 'og:site_name', 'content' => \Yii::$app->params['site']['name']]);
$this->registerMetaTag(['name' => 'og:locale', 'content' => Yii::$app->language]);
$this->registerMetaTag(['name' => 'og:image', 'content' => \Yii::$app->params['site']['url'] . $model->preview_img]);
$this->registerMetaTag(['name' => 'og:image:width', 'content' => '806']);
$this->registerMetaTag(['name' => 'og:image:height', 'content' => '327']);
$this->registerMetaTag(['name' => 'og:image:alt', 'content' => $model->title]);
?>
<div class="post-view">

    <h1><?= $this->title; ?></h1>

    <?php if (UserPermissions::canAdminPost()) : ?>
        <p><i class="fa fa-edit"></i>
            <?= Html::a('Изменить', ['post/update', 'id' => $model->id]); ?></p>
    <?php endif; ?>

    <?php if (!empty($model->preview_img)) : ?>
        <p><img src="/<?= $model->preview_img; ?>" alt="<?= $model->title ?>"></p>
    <?php endif; ?>

    <?php if ($model->isPremium()) : ?>

        <?= Text::hidecut('[cut]',
            Text::hideCut('[premium]', HtmlPurifier::process(Markdown::process($model->content, 'gfm'), ['HTML.Nofollow' => true]))
        ); ?>

        <?php if ($model->ontop) : ?>
            <hr>
            <?= $this->render('/partials/subscribe'); ?>
            <share :title='`<?= \Yii::t('app', 'share_friends') ?>`'></share>
            <widget-ad
                :title='`Реклама`'
                :position='`<?= Ad::SLOT_POST_BOTTOM; ?>`'
                :list='`<?= json_encode(Ad::getRandomAd(Ad::SLOT_POST_BOTTOM)) ?>`'
            ></widget-ad>
        <?php endif; ?>

    <?php else : ?>
        <?= Text::hidecut('[cut]',
            Text::cut('[premium]', HtmlPurifier::process(Markdown::process($model->content, 'gfm'), ['HTML.Nofollow' => true]))
        ); ?>
        <?= $this->render('../partials/premium'); ?>
    <?php endif; ?>

    <?php if ($model->ontop) : ?>
        <?= $this->render('_post_footer', ['model' => $model]); ?>
    <?php endif; ?>

    <?php if ($model->commentsAllowed()) : ?>
        <?= $this->render('_comments', ['model' => $model]); ?>
    <?php endif; ?>

</div>