controllers/AdController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ad\Ad;
use app\models\ad\AdSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\components\UserPermissions;
use yii\web\UploadedFile;

/**
 * AdController implements the CRUD actions for Ad model.
 *
 * @author Alexander Schilling
 */
class AdController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only'  => ['view', 'create', 'update', 'admin', 'delete'],
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => ['view'],
                        'roles'   => ['?', '@'],
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['create', 'update', 'admin', 'delete'],
                        'roles'   => [UserPermissions::ADMIN_AD],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ad models.
     * @return mixed
     */
    public function actionAdmin()
    {
        $searchModel = new AdSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('admin', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new ad model.
     * If creation is successful, the browser will be redirected to the 'admin' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Ad();

        if ($model->load(Yii::$app->request->post())) {

            $model->banner_img_file = UploadedFile::getInstance($model, 'banner_img_file');

            if ($model->save()) {
                return $this->redirect(['admin']);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ad model.
     * If update is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            $model->banner_img_file = UploadedFile::getInstance($model, 'banner_img_file');

            if ($model->save()) {
                return $this->redirect(['admin']);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ad model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['admin']);
    }

    /**
     * Display a single ad
     *
     * @param $slug
     *
     * @return string
     *
     * @throws NotFoundHttpException
     */
    public function actionView($slug)
    {
        $model = Ad::find()->where([
            'status' => Ad::STATUS_PUBLIC,
            'slug' => $slug,
        ])->one();

        if (!$model || !empty($model->code)) {
            throw new NotFoundHttpException('Страница не найдена.');
        }

        $model->countHits('Ad');

        return $this->redirect($model->url);
    }

    /**
     * Finds the ad model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Ad the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Ad::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use app\models\category\Category;
use app\models\Material;
use app\models\Tag;
use Yii;
use app\models\post\Post;
use app\models\post\PostSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\components\UserPermissions;
use yii\web\ForbiddenHttpException;
use app\components\feed\Feed;
use app\components\feed\Item;
use yii\helpers\HtmlPurifier;
use yii\helpers\Markdown;
use yii\helpers\Url;
use app\helpers\Text;
use yii\web\UploadedFile;

/**
 * PostController implements the CRUD actions for Post model.
 *
 * @package app\controllers
 *
 * @author Alexander Schilling
 */
class PostController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only'  => ['index', 'view', 'category', 'tag', 'create', 'admin', 'update', 'delete', 'rss'],
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => ['index', 'view', 'category', 'tag', 'rss'],
                        'roles'   => ['?', '@'],
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['create', 'update', 'admin', 'delete'],
                        'roles'   => [UserPermissions::ADMIN_POST],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all posts
     *
     * @param null $id
     * @return mixed
     */
    public function actionIndex($id = null)
    {

        $this->layout = "/page";

        $searchModel = new PostSearch([
            'sortBy' => (int) $id,
        ]);

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string
     */
    public function actionAdmin()
    {
        $searchModel = new PostSearch();

        $dataProvider = $searchModel->adminSearch(Yii::$app->request->queryParams);

        return $this->render(
            'admin',
            [
                'searchModel'  => $searchModel,
                'dataProvider' => $dataProvider,
            ]
        );
    }

    /**
     * Display a single post model
     *
     * @param $slug
     *
     * @return string
     *
     * @throws NotFoundHttpException
     */
    public function actionView($slug)
    {

        $this->layout = "/blog";

        $model = Post::find()->where([
            'status_id' => Material::STATUS_PUBLIC,
            'slug' => $slug,
        ])->withCommentsCount()->one();

        if (!$model) {
            throw new NotFoundHttpException('Запись не найдена.');
        }

        $model->countHits(Material::MATERIAL_POST_NAME);

        return $this->render('view', ['model' => $model]);
    }

    /**
     * Creates a new Post model
     *
     * If creation is successful, the browser will be redirected to the 'admin' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Post();

        if ($model->load(Yii::$app->request->post())) {

            $model->preview_img_file = UploadedFile::getInstance($model, 'preview_img_file');

            if ($model->save()) {
                Yii::$app->getSession()->setFlash('success', 'Запись добавлена!');
                return $this->redirect(['post/update', 'id' => $model->id]);
            }
        }

        return $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing Post model
     *
     * If update is successful, the browser will be redirected to the 'admin' page
     *
     * @param integer $id
     *
     * @return mixed
     *
     * @throws ForbiddenHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            $model->preview_img_file = UploadedFile::getInstance($model, 'preview_img_file');

            if ($model->save()) {
                Yii::$app->getSession()->setFlash('success', 'Запись сохранена!');

                return $this->redirect(['post/update', 'id' => $model->id]);
            }
        }

        return $this->render('update', ['model' => $model]);
    }

    /**
     * Deletes an existing Post model
     *
     * If deletion is successful, the browser will be redirected to the 'index' page
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['admin']);
    }

    /**
     * Action tag
     *
     * @param $tagName
     *
     * @throws NotFoundHttpException
     *
     * @return string
     */
    public function actionTag($tagName)
    {

        $this->layout = "/page";

        $tag = Tag::findOne(['slug' => $tagName]);

        if (!$tag) {
            throw new NotFoundHttpException("Такой тэг не найден.");
        }

        $searchModel = new PostSearch([
            'tagId' => $tag->id,
        ]);

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('tag', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
            'tag'          => $tag
        ]);
    }

    /**
     * Action category
     *
     * @param $categoryName
     *
     * @return string
     *
     * @throws NotFoundHttpException
     */
    public function actionCategory($categoryName)
    {
        $this->layout = "/page";

        $category = Category::findOne([
            'slug' => $categoryName,
            'material_id' => Material::MATERIAL_POST_ID
        ]);

        if (!$category) {
            throw new NotFoundHttpException("Категория не найдена.");
        }

        $searchModel = new PostSearch([
            'categoryId' => $category->id,
        ]);

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('category', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
            'category'     => $category
        ]);
    }

    /**
     * List of posts for rss
     *
     * @return void
     */
    public function actionRss(): void
    {

        /** @var Post[] $posts */
        $posts = Post::find()->where(['status_id' => Post::STATUS_PUBLIC, 'ontop' => Post::SHOW_ON_TOP])->orderBy('datecreate DESC')->limit(10)->all();

        $feed = new Feed();
        $feed->title = \Yii::$app->params['site']['name'];
        $feed->link = Url::to(\Yii::$app->params['site']['url']);
        $feed->selfLink = Url::to(['post/rss'], true);
        $feed->description = 'RSS лента сайта ' .\Yii::$app->params['site']['name'];
        $feed->language = Yii::$app->language;
        $feed->setWebMaster(\Yii::$app->params['adminEmail'], \Yii::$app->params['site']['author']);
        $feed->setManagingEditor(\Yii::$app->params['adminEmail'], \Yii::$app->params['site']['author']);

        foreach ($posts as $post) {
            $item = new Item();
            $item->title = $post->title;
            $item->link = Url::to(['post/view', 'slug' => $post->slug], true);
            $item->guid = Url::to(['post/view', 'slug' => $post->slug], true);
            $item->description = Text::cut('[cut]', Text::cut('[premium]', HtmlPurifier::process(Markdown::process($post->content, 'gfm'), ['HTML.Nofollow' => true])));
            $item->pubDate = $post->datecreate;
            $item->setAuthor(\Yii::$app->params['adminEmail'], $post->user->username);
            $feed->addItem($item);
        }

        $feed->render();
    }

    /**
     * Finds the Post model based on its primary key value
     *
     * If the model is not found, a 404 HTTP exception will be thrown
     *
     * @param integer $id
     *
     * @return Post the loaded model
     *
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Статья не найдена.');
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\components\UserPermissions;
use yii\authclient\Collection;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * UserController implements the CRUD actions for User model.
 *
 * @package app\controllers
 *
 * @author Alexander Schilling <dignityinside@gmail.com>
 */
class UserController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {

        return [
            'access' => [
                'class' => AccessControl::class,
                'only'  => ['update'],
                'rules' => [
                    [
                        'allow'   => true,
                        'actions' => ['view', 'update'],
                        'roles'   => ['@'],
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['admin', 'create', 'delete'],
                        'roles'   => [UserPermissions::ADMIN_USERS],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     *
     * @return mixed
     */
    public function actionAdmin()
    {

        $dataProvider = new ActiveDataProvider(
            [
                'query' => User::find(),
            ]
        );

        return $this->render(
            'admin',
            [
            'dataProvider' => $dataProvider,
            ]
        );
    }

    /**
     * Displays user profile
     *
     * @param integer $id
     *
     * @return mixed
     *
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {

        $this->layout = "/page";

        /** @var User $user */
        $user = User::findOne($id);

        if (!$user) {
            throw new NotFoundHttpException('Пользователь не найден.');
        }

        $authClients = [];

        if (Yii::$app->user->id == $user->id) {
            // get clients user isn't connected with yet
            $auths = $user->auths;

            /** @var Collection $clientCollection */
            $clientCollection = Yii::$app->authClientCollection;

            $authClients = $clientCollection->getClients();

            foreach ($auths as $auth) {
                unset($authClients[$auth->source]);
            }
        }

        return $this->render(
            'view',
            [
            'model'       => $user,
            'authClients' => $authClients,
            ]
        );
    }

    /**
     * Updates an existing User model.
     *
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     *
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     *
     * @return mixed
     */
    public function actionUpdate($id)
    {

        $model = $this->findModel($id);

        if (!UserPermissions::canEditUser($model)) {
            throw new ForbiddenHttpException('Вы не можете редактировать этот профиль.');
        }

        if (UserPermissions::canAdminUsers()) {
            $model->scenario = User::SCENARIO_ADMIN;
        } else {
            $model->scenario = User::SCENARIO_UPDATE;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render(
            'update',
            [
            'model' => $model,
            ]
        );
    }

    /**
     * Deletes an existing User model.
     *
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionDelete($id)
    {

        $model = $this->findModel($id);
        $model->status = User::STATUS_DELETED;
        $model->save();

        return $this->redirect(['admin']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     *
     * @return User the loaded model
     *
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {

        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/partials/counter.php
<!-- Yandex.Metrika counter --> <script type="text/javascript" > (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)}; m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)}) (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(15912202, "init", { id:15912202, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); </script> <noscript><div><img src="https://mc.yandex.ru/watch/<?= \Yii::$app->params['yandexMetrikaId']; ?>" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->

views/layouts/partials/head.php
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<?= \Yii::$app->params['googleTagManager']; ?>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '<?= \Yii::$app->params['googleTagManager']; ?>');
</script>

views/layouts/partials/nav.php
<?php

    use app\components\UserPermissions;
    use yii\bootstrap\Nav;
    use yii\bootstrap\NavBar;
    use yii\helpers\Html;

    NavBar::begin(
        [
            'brandLabel' => Html::img('/img/rooland-logo.png'),
            'options'    => [
                'class' => 'navbar-inverse',
            ],
        ]
    );

    $menuItems[] = ['label' => \Yii::t('app/blog', 'menu_label_index_blog'), 'url' => ['/post/index']];

    // $menuItems[] = ['label' => \Yii::t('app/forum', 'menu_label_forum_index'), 'url' => ['/forum/index']];

    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => \Yii::t('app', 'menu_label_login'), 'url' => ['/login']];
    } else {

        $menuItems[] = [
            'label' => \Yii::t('app', 'menu_label_profile'),
            'url' => ['/user/view', 'id' => \Yii::$app->user->id]
        ];

        if (Yii::$app->user->can('admin')) {

            $menuItems[] = [
                'label' => \Yii::t('app', 'menu_label_panel'), 'items' => [
                    [
                        'label' => \Yii::t('app/blog', 'menu_label_admin_blog'),
                        'url' => ['/post/admin'],
                        'visible' => UserPermissions::canAdminPost()
                    ],
                    [
                        'label' => \Yii::t('app/comments', 'menu_label_admin_comments'),
                        'url' => ['/comment-admin/manage/index'],
                        'visible' => UserPermissions::canAdminPost()
                    ],
                    [
                        'label' => \Yii::t('app/forum', 'menu_label_forum_admin'),
                        'url' => ['/forum/admin'],
                        'visible' => UserPermissions::canAdminForum()
                    ],
                    [
                        'label' => \Yii::t('app/category', 'menu_label_admin_category'),
                        'url' => ['/category/admin'],
                        'visible' => UserPermissions::canAdminCategory()
                    ],
                    [
                        'label' => \Yii::t('app', 'menu_label_user_admin'),
                        'url' => ['/user/admin'],
                        'visible' => UserPermissions::canAdminUsers()
                    ],
                    [
                        'label' => \Yii::t('app', 'menu_label_ad_admin'),
                        'url' => ['/ad/admin'],
                        'visible' => UserPermissions::canAdminAd()
                    ],
                ],
            ];

        }

        $menuItems[] = [
            'label' => \Yii::t('app', 'logout_({username})', [
                'username' => Yii::$app->user->identity->username,
            ]),
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post']
        ];

    }

    echo Nav::widget(
        [
            'options' => ['class' => 'navbar-nav navbar-left'],
            'items'   => $menuItems,
        ]
    );

    echo $this->render('../partials/search.php');

    NavBar::end();

views/layouts/partials/search.php
<div class="nav navbar-nav navbar-right">
    <div class="widget-content search">
        <?= \yii\helpers\Html::beginForm('/search', 'get', ['id' => 'search-form-nav', 'class' => 'navbar-form']) ?>
            <div class="form-group nospace">
                <input type="text" class="form-control" id="search" name="text" placeholder="Поиск" autocomplete="off" value="">
                <input type="hidden" name="searchid" value="2328465"/>
                <input type="hidden" name="l10n" value="ru"/>
                <input type="hidden" name="reqenc" value="utf-8"/>
            </div>
        <?= \yii\helpers\Html::endForm() ?>
    </div>
</div>