controllers/ForumController.php
<?php

namespace app\controllers;

use app\components\UserPermissions;
use app\models\category\Category;
use app\models\forum\Forum;
use app\models\forum\ForumSearch;
use app\models\forum\ForumCategories;
use app\models\Material;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ForumController implements the CRUD actions for Forum model.
 *
 * @author Alexander Schilling
 */
class ForumController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {

        return [
            'access' => [
                'class' => AccessControl::class,
                'only'  => ['index', 'topics', 'topic', 'user', 'create', 'update', 'my', 'admin', 'delete'],
                'rules' => [
                    [
                        'actions' => ['index', 'topics', 'topic', 'user'],
                        'allow'   => true,
                        'roles'   => ['?', '@'],
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['create', 'update', 'my'],
                        'roles'   => ['@'],
                    ],
                    [
                        'allow'   => true,
                        'actions' => ['admin', 'delete'],
                        'roles'   => [UserPermissions::ADMIN_FORUM],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Returns actions
     *
     * @return array
     */
    public function actions(): array
    {
        $this->layout = "/forum";

        return [
            'error'   => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Lists of all topics (admin view)
     *
     * @return mixed
     */
    public function actionAdmin()
    {

        $this->layout = "/main";

        $dataProvider = new ActiveDataProvider(
            [
                'query' => Forum::find()->orderBy('created_at DESC')->withCommentsCount(),
                'pagination' => [
                    'pageSize' => \Yii::$app->params['forum']['adminPageSize'],
                ],
            ]
        );

        return $this->render('admin', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * List current user topics
     *
     * @return string
     */
    public function actionMy()
    {

        $query = Forum::find()->where(['user_id' => \Yii::$app->user->id])->withCommentsCount()->orderBy('created_at DESC');

        $dataProvider = new ActiveDataProvider(
            [
                'query'      => $query,
                'pagination' => [
                    'pageSize' => \Yii::$app->params['forum']['myPageSize'],
                ],
            ]
        );

        return $this->render('my', ['dataProvider' => $dataProvider]);
    }

    /**
     * Creates a topic
     *
     * If creation is successful, the browser will be redirected to the 'my' page.
     *
     * @param int|null $id
     *
     * @return mixed
     */
    public function actionCreate(?int $id = null)
    {

        $categoryId = $id !== null ? $id : 0;

        $model = new Forum();

        $model->scenario = UserPermissions::canAdminForum() ? Material::SCENARIO_ADMIN : Material::SCENARIO_CREATE;

        if ($model->load(\Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['forum/my']);
        }

        return $this->render('create', ['model' => $model, 'categoryId' => $categoryId]);
    }

    /**
     * Updates an existing topic
     *
     * If update is successful, the browser will be redirected to the 'view' page
     *
     * @param integer $id
     *
     * @return mixed
     *
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     */
    public function actionUpdate(int $id)
    {

        $model = $this->findModel($id);

        if (!UserPermissions::canEditForum($model)) {
            throw new ForbiddenHttpException('Вы не можете редактировать эту тему.');
        }

        $model->scenario = UserPermissions::canAdminForum() ? Material::SCENARIO_ADMIN : Material::SCENARIO_UPDATE;

        if ($model->load(\Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/forum/topic', 'id' => $model->id]);
        }

        return $this->render('update', ['model' => $model,]);
    }

    /**
     * List of all categories
     *
     * @return string
     */
    public function actionIndex()
    {

        $searchModel = new ForumCategories();

        return $this->render('index', ['dataProvider' => $searchModel->search()]);
    }

    /**
     * List of all topics filtered by category name and sorted by...
     *
     * @param string|null $categoryName
     * @param string|null $sortBy
     *
     * @return string
     *
     * @throws NotFoundHttpException
     */
    public function actionTopics(string $categoryName = null, string $sortBy = null)
    {

        if ($categoryName === null) {
            return $this->redirect(['forum/index']);
        }

        if ($categoryName === 'new') {
            $searchModel = new ForumSearch(['sortBy' => $sortBy]);

            return $this->render('topics', [
                'searchModel' => $searchModel,
                'dataProvider' => $searchModel->search(\Yii::$app->request->queryParams)
            ]);
        }

        // filter by category name

        $category = Category::findOne(['slug' => $categoryName, 'material_id' => Material::MATERIAL_FORUM_ID]);

        if (!$category) {
            throw new NotFoundHttpException("Форум не найден.");
        }

        // sort by

        if ($sortBy === null || !in_array($sortBy, ForumSearch::SORT_BY)) {
            $searchModel = new ForumSearch(['categoryId' => $category->id]);
        } else {
            $searchModel = new ForumSearch([
                'categoryId' => $category->id,
                'sortBy' => $sortBy
            ]);
        }

        return $this->render('topics', [
            'searchModel' => $searchModel,
            'dataProvider' => $searchModel->search(\Yii::$app->request->queryParams),
            'categoryModel' => $category
        ]);
    }

    /**
     * Lists all topics from user
     *
     * @param string|null $userName
     *
     * @return mixed
     *
     * @throws NotFoundHttpException
     */
    public function actionUser(string $userName = null)
    {

        $user = User::findOne(['username' => $userName]);

        if (!$user) {
            throw new NotFoundHttpException("Пользователь ещё не опубликовал ни одной темы.");
        }

        $searchModel = new ForumSearch(['userId' => $user->id]);

        return $this->render('user', [
            'searchModel' => $searchModel,
            'dataProvider' => $searchModel->search(\Yii::$app->request->queryParams),
            'userName' => $user->username
        ]);
    }

    /**
     * Action topic
     *
     * @param int $id Id
     *
     * @return string
     *
     * @throws NotFoundHttpException
     */
    public function actionTopic(int $id)
    {

        $model = Forum::findOne([
            'id' => $id,
            'status_id' => Material::STATUS_PUBLIC
        ]);

        if (!$model) {
            throw new NotFoundHttpException("Тема не найдена.");
        }

        $model->countHits(Material::MATERIAL_FORUM_NAME);

        return $this->render('topic', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing topic model.
     *
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     *
     * @param integer $id
     *
     * @return mixed
     *
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete(int $id)
    {

        $this->findModel($id)->delete();

        return $this->redirect(['admin']);
    }

    /**
     * Finds the forum model based on its primary key value.
     *
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param int $id
     *
     * @return Forum the loaded model
     *
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel(int $id)
    {

        if (($model = Forum::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Форум не найден.');
    }
}

views/forum/_comments.php
<?php

use yii\helpers\Url;
use demi\comments\frontend\widgets\Comments;
use app\models\forum\Forum;

/* @var $this yii\web\View */
/** @var $model Forum */

?>

<?php if ($model->allow_comments) : ?>
    <?= Comments::widget(
        [
            'materialType' => \app\models\Material::MATERIAL_FORUM_ID,
            'materialId' => $model->id,
            'options' => [
                'class' => 'comments list-unstyled',
            ],
            'nestedOptions' => [
                'class' => 'comments reply list-unstyled',
            ],
            'clientOptions' => [
                'deleteComfirmText' => \Yii::t('app/comments', 'delete_confirm_text'),
                'updateButtonText' => \Yii::t('app/comments', 'update_button_text'),
                'cancelUpdateButtonText' => \Yii::t('app/comments', 'cancel_update_button_text'),
                'commentTextSelector' => '.comment-text > div',
            ],
            'maxNestedLevel' => 5,
            'materialViewUrl' => Url::to(['topic', 'id' => $model->id]),
            'formConfig' => [
                'enableClientValidation' => true,
                'enableAjaxValidation' => false,
            ],
        ]
    ); ?>

<?php endif;

views/forum/_form.php
<?php

use app\components\UserPermissions;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\category\Category;
use app\assets\MarkdownEditorAsset;

/* @var $this yii\web\View */
/* @var $model app\models\forum\Forum */
/* @var $form yii\widgets\ActiveForm */
/** @var int $categoryId */

MarkdownEditorAsset::register($this);

$categoryId = !empty($categoryId) ? $categoryId : 0;

?>

<div class="forum-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'category_id')->dropDownList(
        ArrayHelper::map(Category::getAllCategories(\app\models\Material::MATERIAL_FORUM_ID), 'id', 'name'),
        ['prompt' => \Yii::t('app/forum', 'forum_select_category'),
         'options' => [(string)$categoryId => ['Selected' => true]]]
    ); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field(
        $model,
        'content',
        [
            'template' => "{label}\n{error}\n{input}\n{hint}"
        ]
    )->textarea(['class' => 'markdown-editor']) ?>

    <?= $form->field($model, 'allow_comments')->dropDownList([
        '1' => \Yii::t('app/comments', 'text_allow_comments_yes'),
        '0' => \Yii::t('app/comments', 'text_allow_comments_no')
    ]) ?>

    <?php if (UserPermissions::canAdminForum()) : ?>

        <?= $form->field($model, 'pinned')->dropDownList([
            '0' => \Yii::t('app', 'no'),
            '1' => \Yii::t('app', 'yes')
        ]) ?>

        <?= $form->field($model, 'status_id')->dropDownList($model->getStatuses()) ?>
        <?= $form->field($model, 'meta_description')->textInput(['maxlength' => true]) ?>
    <?php endif ?>

    <div class="form-group">
        <?= Html::submitButton(
            $model->isNewRecord ? \Yii::t('app', 'button_save') : \Yii::t('app', 'button_update'),
            ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']
        ) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/forum/_index_topics.php
<?php

use app\helpers\Text;
use yii\helpers\Url;

/** @var $this yii\web\View */
/** @var $model app\models\forum\Forum */

if (!empty($model->user_id)) {
    $user['link'] = Url::toRoute(['forum/user/' . $model->user->username]);
    $user['name'] = $model->user->username;
} else {
    $user['link'] = '';
    $user['name'] = \Yii::t('app', 'user_anonym');
}

?>

<forum-topics-items
    :data='`<?= Text::arrayToJson([
        'pinned'         => $model->pinned ? true : false,
        'allow_comments' => $model->allow_comments ? true : false,
        'title'          => $model->title,
        'url'            => Url::toRoute(['forum/topic', 'id' => $model->id]),
        'createdAt'      => $model->getFormattedCreatedAt(),
        'user'       => $user,
        'category'   => [
            'name' => $model->category->name,
            'link' => Url::toRoute(['/forum/topics/' . $model->category->slug]),
        ],
        'comments' => $model->commentsCount,
        'hits' => $model->hits
    ]); ?>`'
></forum-topics-items>

views/forum/admin.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/** @var $this yii\web\View */
/** @var $dataProvider yii\data\ActiveDataProvider */

$this->title = \Yii::t('app/forum', 'page_forum_admin_title');

$this->params['breadcrumbs'][] = ['label' => \Yii::t('app/forum', 'breadcrumbs_forum_index'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="forum-admin">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'title',
            [
                'attribute' => 'user_id',
                'label'     => \Yii::t('app', 'author'),
                'value'     => function ($model) {
                    return $model->user->username ?? \Yii::t('app', 'user_anonym');
                }
            ],
            [
                'attribute' => 'created_at',
                'label' => \Yii::t('app', 'columns_label_created'),
                'value' => function ($model) {
                    return $model->getFormattedCreatedAt();
                }
            ],
            [
                'attribute' => 'status_id',
                'label'     => \Yii::t('app', 'columns_label_status'),
                'value'     => function ($model) {
                    return $model->getStatusLabel();
                }
            ],
            [
                'attribute' => 'hits',
                'label' => \Yii::t('app', 'columns_label_hits'),
                'value' => function ($model) {
                    return $model->hits;
                }
            ],
            [
                'attribute' => \Yii::t('app', 'columns_label_comments'),
                'label' => 'Ответы',
                'value' => function ($model) {
                    return $model->commentsCount;
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}{update}{delete}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', '/forum/topic/' . $model->id, ['target' => '_blank']);
                    },
                ],
            ],
        ],
    ]); ?>
</div>

views/forum/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\forum\Forum */

$this->title = \Yii::t('app/forum', 'page_forum_create_title');

$this->params['breadcrumbs'][] = ['label' => \Yii::t('app/forum', 'breadcrumbs_forum_index'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => \Yii::t('app/forum', 'breadcrumbs_forum_my'), 'url' => ['my']];
$this->params['breadcrumbs'][] = Html::encode($this->title);

?>
<div class="forum-create">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', ['model' => $model, 'categoryId' => $categoryId]) ?>
</div>

views/forum/index.php
<?php

use app\helpers\Text;
use app\models\forum\Forum;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = \Yii::t('app/forum', 'page_forum_index_title');

$this->registerMetaTag(['name' => 'description', 'content' => 'Форум сайта ' . \Yii::$app->params['site']['name']]);
$this->registerMetaTag(['name' => 'robots', 'content' => 'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1']);

$this->registerLinkTag(['rel' => 'canonical', 'href' => Url::to(['/forum'], true)]);

$this->params['breadcrumbs'][] = \Yii::t('app/forum', 'breadcrumbs_forum_index');

?>

<forum-categories-list-item
    :title='`<?= $this->title; ?>`'
    :empty-text='`<?= \Yii::t('app/forum', 'forum_index_list_empty_text'); ?>`'
    :list='`<?= Text::arrayToJson(Forum::getCategoriesList()); ?>`'
    :buttons='`<?= Text::arrayToJson([
        [
            'name'  => \Yii::t('app/forum', 'forum_button_new_topic'),
            'url'  => Url::toRoute(['create']),
            'icon'  => 'fas fa-plus',
            'class' => 'btn btn-success',
        ],
        [
            'name'  => \Yii::t('app/forum', 'forum_button_new_topics'),
            'url'  => Url::toRoute(['topics', 'categoryName' => 'new']),
            'icon'  => 'fa fa-clock',
            'class' => 'btn btn-default',
        ],
        [
            'name'  => \Yii::t('app/forum', 'forum_button_my_topics'),
            'url'  => Url::toRoute(['my']),
            'icon'  => 'fas fa-crown',
            'class' => 'btn btn-default',
        ],
    ]); ?>`'
></forum-categories-list-item>

views/forum/my.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = \Yii::t('app/forum', 'page_forum_my_title');

$this->params['breadcrumbs'][] = ['label' => \Yii::t('app/forum', 'breadcrumbs_forum_index'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="forum-admin">

    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Html::a('<i class="fas fa-plus"></i> ' . \Yii::t('app/forum', 'forum_button_new_topics'),
            ['create'], ['class' => 'btn btn-success']); ?></p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'title',
            [
                'attribute' => 'status_id',
                'label'     => \Yii::t('app', 'columns_label_status'),
                'value'     => function ($model) {
                    return $model->getStatusLabel();
                }
            ],
            [
                'attribute' => 'created_at',
                'label' => \Yii::t('app', 'columns_label_created'),
                'value' => function ($model) {
                    return $model->getFormattedCreatedAt();
                }
            ],
            [
                'attribute' => 'comments',
                'label' => \Yii::t('app', 'columns_label_comments'),
                'value' => function ($model) {
                    return $model->commentsCount;
                }
            ],
            [
                'attribute' => 'hits',
                'label' => \Yii::t('app', 'columns_label_hits'),
                'value' => function ($model) {
                    return $model->hits;
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}{update}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', '/forum/topic/' . $model->id, ['target' => '_blank']);
                    },
                ],
            ],
        ],
    ]); ?>
</div>

views/forum/topic.php
<?php

use app\components\UserPermissions;
use app\helpers\Text;
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\Markdown;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\forum\Forum */

$this->title = Html::encode($model->title);

$this->params['breadcrumbs'][] = ['label' => \Yii::t('app/forum', 'breadcrumbs_forum_index'),
                                  'url' => ['/forum/index']];
$this->params['breadcrumbs'][] = ['label' => $model->category->name,
                                  'url' => ['/forum/topics', 'categoryName' => $model->category->slug]];
$this->params['breadcrumbs'][] = $this->title;

$this->registerMetaTag(['name' => 'title', 'content' => $model->title]);
$this->registerMetaTag(['name' => 'description', 'content' => Html::encode($model->meta_description)]);
$this->registerMetaTag(['name' => 'robots', 'content' => 'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1']);

$this->registerLinkTag(['rel' => 'canonical', 'href' => Url::to(['topic', 'id' => $model->id], true)]);

if (!empty($model->user_id)) {
    $user['link'] = Url::toRoute(['forum/user/' . $model->user->username]);
    $user['name'] = $model->user->username;
} else {
    $user['link'] = '';
    $user['name'] = \Yii::t('app', 'user_anonym');
}

?>

<forum-topics-item
    :title='`<?= $this->title; ?>`'
    :data='`<?= Text::arrayToJson([
        'edit'       => [
            'canEdit' => UserPermissions::canAdminForum() || UserPermissions::canEditForum($model),
            'link'    => Url::toRoute(['forum/update', 'id' => $model->id]),
            'text'    => \Yii::t('app', 'button_update'),
        ],
        'id'         => $model->id,
        'createdAt'  => $model->getFormattedCreatedAt(),
        'shareTitle' => \Yii::t('app', 'share_friends'),
        'user'       => $user,
        'category'   => [
            'name' => $model->category->name,
            'link' => Url::toRoute(['/forum/topics/' . $model->category->slug]),
        ],
    ]); ?>`'
>
    <div slot="content">
        <?= HtmlPurifier::process(Markdown::process($model->content, 'gfm'), ['HTML.Nofollow' => true]) ?>
    </div>
    <div slot="comments">
        <?= $this->render('_comments', ['model' => $model]); ?>
    </div>
</forum-topics-item>

views/forum/topics.php
<?php

use app\helpers\Text;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var \app\models\category\Category $categoryModel */

$categoryName = isset($categoryModel)
    ? Html::encode($categoryModel->name)
    : \Yii::t('app/forum', 'forum_new_topics_text');
$categoryId = isset($categoryModel) ? $categoryModel->id : 0;
$categorySlug = isset($categoryModel) ? $categoryModel->slug : 'new';

$this->title = isset($categoryModel)
    ? \Yii::t('app/forum', 'page_forum_topic_title') . ' - ' . $categoryName
    : \Yii::t('app/forum', 'forum_new_topics_text');

if (isset($categoryModel)) {
    $this->registerMetaTag(['name' => 'description', 'content' => $categoryModel->description]);
    $this->registerMetaTag(['name' => 'robots', 'content' => 'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1']);

    $this->registerLinkTag(['rel' => 'canonical', 'href' => Url::to(['/forum/topics/' . $categoryModel->slug], true)]);
}

$this->params['breadcrumbs'][] = ['label' => \Yii::t('app/forum', 'breadcrumbs_forum_index'), 'url' => ['index']];
$this->params['breadcrumbs'][] = isset($categoryModel) ? $categoryName : \Yii::t('app/forum', 'forum_new_topics_text');

?>

<forum-topics-list
    :title='`<?= $this->title; ?>`'
    :buttons='`<?= Text::arrayToJson([
        [
            'icon' => 'fas fa-plus',
            'name' => \Yii::t('app/forum', 'forum_button_new_topic'),
            'url' => Url::toRoute(['create', 'id' => $categoryId]),
            'class' => 'btn btn-success',
        ],
        [
            'icon' => 'fa fa-folder',
            'name' => \Yii::t('app/forum', 'forum_button_categories'),
            'url' => Url::toRoute(['/forum']),
            'class' => 'btn btn-default',
        ],
        [
            'icon' => 'fa fa-clock',
            'name' => \Yii::t('app/forum', 'forum_button_new_topics'),
            'url' => Url::toRoute(['topics', 'categoryName' => 'new']),
            'class' => 'btn btn-default',
        ],
        [
            'icon' => 'fas fa-crown',
            'name' => \Yii::t('app/forum', 'forum_button_my_topics'),
            'url' => Url::toRoute(['my']),
            'class' => 'btn btn-default',
        ],
    ]); ?>`'
    :material-sort='`<?= Text::arrayToJson([
        [
            'icon' => 'fa fa-clock',
            'name' => \Yii::t('app', 'sort_new'),
            'url' => Url::toRoute(['/forum/topics/', 'categoryName' => $categorySlug])
        ],
        [
            'icon' => 'fa fa-eye',
            'name' => \Yii::t('app', 'sort_hits'),
            'url' => Url::toRoute(['/forum/topics/' . $categorySlug . '/hits'])
        ],
        [
            'icon' => 'fa fa-comments',
            'name' => \Yii::t('app', 'sort_comments'),
            'url' => Url::toRoute(['/forum/topics/' . $categorySlug . '/comments'])
        ],
        [
            'icon' => 'fas fa-comment-slash',
            'name' => \Yii::t('app/forum', 'forum_sort_no_answer'),
            'url' => Url::toRoute(['/forum/topics/' .  $categorySlug . '/unanswered'])
        ],
    ]); ?>`'
    :material-show="`<?= $dataProvider->totalCount >= 2; ?>`"
>
    <div slot="list-view">
        <?= ListView::widget(
            [
                'dataProvider' => $dataProvider,
                'emptyText'    => \Yii::t('app/forum', 'forum_category_list_empty_text'),
                'itemView'     => '_index_topics',
                'layout'       => "{items}{pager}",
            ]
        ); ?>
    </div>
</forum-topics-list>

views/forum/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\forum\Forum */

$this->title = 'Обновить тему';

$this->params['breadcrumbs'][] = ['label' => \Yii::t('app/forum', 'breadcrumbs_forum_index'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => \Yii::t('app/forum', 'breadcrumbs_forum_my'), 'url' => ['my']];
$this->params['breadcrumbs'][] = \Yii::t('app', 'breadcrumbs_label_update');

?>

<div class="forum-update">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', ['model' => $model]) ?>
</div>

views/forum/user.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

/** @var $this yii\web\View */
/** @var $dataProvider yii\data\ActiveDataProvider */
/** @var string $userName */

$this->title = \Yii::t('app/forum', 'forum_user_topics') . ' ' . Html::encode($userName);

$this->params['breadcrumbs'][] = ['label' => \Yii::t('app/forum', 'breadcrumbs_forum_index'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<forum-topics-list
    :title='`<?= $this->title; ?>`'>
    <div slot="list-view">
        <?= ListView::widget(
            [
                'dataProvider' => $dataProvider,
                'emptyText' => \Yii::t('app/forum', 'forum_topics_list_empty_text'),
                'itemView' => '_index_topics',
                'layout' => "{items}{pager}",
            ]
        ); ?>
    </div>
</forum-topics-list>